CREATE OR REPLACE DATABASE NotiteDb;

USE NotiteDb;

CREATE TABLE Notite (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titlu VARCHAR(256) NOT NULL,
    continut MEDIUMTEXT NOT NULL,
    autor VARCHAR(256) NOT NULL
);